// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffuuwaeneyqkvckfjgme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmdXV3YWVuZXlxa3Zja2ZqZ21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTc4NTQsImV4cCI6MjA3NDkzMzg1NH0.TMA15Lc7NrtcEmPtWFJtR2ZHmLUi3ZGJkG6aI2sPvzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});